### ISSUE TITLE
Execute multiple actions with a single button

### ISSUE THREAD

**Issue by glittery11** [team-forms/community#21]
I want to trigger more than one button action with a single button.
I am trying to disable the container of a row by pressing the button to fire an event,
and then immediately url post the row.
Is this possible?

**Comment by Erin-Dwyer** [comment]
Hi @glittery11,
 
Would you mind providing a little more context on what you ultimatly want to achieve that way we might be able to advise on a simpler solution that aligns with Team Forms best practise?

Typically if you are using buttons to peform some custom action then the button is configure to run some JavaScript code when pressed. If that is the case, instead of trigging other buttons using your button you should instead add or duplicate the code from your other buttons into your current button. 

From your question it sounds like you might be wanting to trigger an event and then some additional actions on a single button. To do so you can utilize Javascript code for example:

```
instance.email('myCustomEvent') // This will trigger an event called myCustomEvent
instance.emit('submitButton') //This will submit the form
```

With that said I still think we should first look at what you want to achive in your form first  as there may be a far simpler option then firing custom event.

**Comment by glittery11** [comment]
hello.
I thought it might be possible to put a button on a datagrid to submit a mini-post for a row.
If possible, I would like to disable the grid row when the button is clicked and extract the content for that row via power automate.

but now that I think about it, I need to be able to extract the index of the current row...

**Comment by glittery11** [comment]
I just had another idea.
I'll try it and let you know if it doesn't work.
Thanks.

**Comment by Erin-Dwyer** [comment]
Interested to hear if you find a simpler option to achieve the outcome. It is certinly possiable to do what you have described, however I would suggest you see if there is a simpler option :) 


1. Drag a new checkbox component into your data-grid called "disabledRow" and configure it to be hidden (display -> hidden). This hidden checkbox will control if the row should be disabled.
3. In the custom CSS for your form, add in the following css that will automatically disable data-grid rows when ever the disableRow checkbox is ticked.
    ```
    tr:has(.checkbox>label>[checked="true"]) {
        background-color: rgba(224, 224, 224, 0.8);
        pointer-events:none;
    }
    ```
        
    ![image](https://github.com/team-forms/community/assets/154988548/2d204bfc-511d-4c67-8c64-7afdbde6ab02)

5. Setup a power automate workflow from a "When a HTTP request is recieved" trigger and "POST" method.
![image](https://github.com/team-forms/community/assets/154988548/1c42dd4f-57f0-4486-a7f1-82f2005e2d8e)
2. Within your custom button (located on the data-grid row) use the following javascript to disable the set the value of disableRow and send the row data to the power automate flow setup earlier.

Notice how the "row" variable is used to access the data from the current row.

    ```
    row.disableRow = true
    instance.parent.redraw()
    fetch("InsertPowerAutomateWorkflowUrlHere",
    {
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },
        method: "POST",
        body: JSON.stringify(row)
    })
    ```
